server:
  port: 8888

spring:
  config:
    name: config-server
  security:
    user:
      name: "root"
      password: "s3cr3t"

management:
  endpoints:
    web:
      exposure:
        include: "*"
